server:
  port: 8080

spring:
  application:
    name: 024-pet-adoption
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/024_pet_adoption?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.xiaou.pet.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.xiaou.pet.mapper: debug
