server:
  port: 8080

spring:
  application:
    name: study-room-system

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_room?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

# JWT配置
jwt:
  secret: studyRoomJwtSecretKey2024!@#$%^&*()
  expiration: 86400000  # 24小时

# 二维码配置
qrcode:
  width: 200
  height: 200

logging:
  level:
    com.xiaou.studyroom: debug
    org.springframework.web: debug